### ISSUE TITLE
Mock Exam 1 Question 6 - showing failed

### ISSUE THREAD

**Issue by oscargarciajr** [kodekloudhub/certified-kubernetes-security-specialist-cks-course#22]
The questions showing failed even if I just followed the solution presented.

**Comment by Tej-Singh-Rana** [comment]
Hi @oscargarciajr ,
It's happening with the new version of Falco. 
You can check the details here - https://github.com/falcosecurity/falco/issues/2048

We are working on a fix. 

Regards,
Team KodeKloud

**Comment by Tej-Singh-Rana** [comment]
This issue has been resolved. Please give it another try.
